<?php
?>

<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
  <p>La plantilla de blog para <a href="https://getbootstrap.com/">Bootstrap</a> está diseñada por <a href="https://twitter.com/mdo"><bdi lang="en" dir="ltr">@mdo</bdi></a>.</p>
  <p class="mb-0">
    <a href="#">Volver al principio</a>
  </p>
</footer>
<script src="<?php echo $config->urls->templates;?>js/bootstrap.bundle.min.js"></script>

    </body>
</html>